setup.py: generate package list dynamically
Fixes import error due to missing firedrake.adjoint in the list
and future-proofs the list:

	>>> import firedrake
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/.../usr/lib/python3.8/site-packages/firedrake/__init__.py", line 59, in <module>
	    from firedrake.assemble import *
	...
	  File "/.../usr/lib/python3.8/site-packages/firedrake/interpolation.py", line 15, in <module>
	    from firedrake.adjoint import annotate_interpolate
	ModuleNotFoundError: No module named 'firedrake.adjoint'

Signed-off-by: Alexei Colin <acolin@isi.edu>